andrewmiller0/textbook

client/index.html, server/api/student/student.model.js, server/api/student/student.spec.js, server/config/seed.js, server/config/socketio.js, server/routes.js
=> 2 student schema closes #2

server/api/schedMsg/schedMsg.model.js, server/api/schedMsg/schedMsg.spec.js, server/api/student/student.spec.js
=> schedule message schema closes #6

client/app/classroom/classroom.service.js, client/app/classroom/classroom.service.spec.js, client/app/conversation/conversation.service.js, client/app/conversation/conversation.service.spec.js, client/app/schedMsg/schedMsg.service.js, client/app/schedMsg/schedMsg.service.spec.js, client/app/student/student.service.js, client/app/student/student.service.spec.js
=> generated services closes #22

client/app/classroom/classroom.service.js, client/app/conversation/conversation.service.js, client/app/schedMsg/schedMsg.service.js, client/app/student/student.service.js
=> changed to factory

client/app/classroom/classroom.service.js, client/index.html, server/api/classroom/classroom.controller.js, server/api/classroom/index.js
=> closes #17

client/app/student/student.service.js
Please review.  We will not need population methods on the student because it has no object id references so just an update method on the resource will work for now
=> put resource on student closes #18

client/app/account/login/login.html, client/app/account/settings/settings.html, client/app/account/signup/signup.html, client/app/app.js, client/app/app.scss, client/app/main/main.html, client/app/main/main.scss, client/components/navbar/navbar.controller.js, client/components/navbar/navbar.html, client/index.html
=> 14 styling closes #14

server/api/contact/contact.controller.js, server/api/contact/contact.model.js, server/api/contact/contact.socket.js, server/api/contact/contact.spec.js, server/api/contact/index.js, server/api/conversation/conversation.model.js, server/api/student/student.model.js, server/api/student/student.spec.js, server/config/socketio.js, server/routes.js
=> closes #29 (schema redesign)

client/app/account/settings/settings.controller.js, client/app/account/settings/settings.html, client/app/app.js, client/app/app.scss, client/app/main/main.scss, client/app/student/student.service.js, client/components/navbar/navbar.html, client/components/tel/tel.filter.js, client/components/tel/tel.filter.spec.js, client/index.html, server/api/user/user.controller.js, server/config/seed.js
Here is my pull request.  I've edited the settings view and also created a telephone filter which we might need to use in later areas of the app.  Let me know if you have any questions!
=> 30 create teacher admin closes #30

client/app/contact/contact.service.js, client/app/contact/contact.service.spec.js
=> closes #35

client/app/account/account.js, client/app/account/settings/newClassroom/newclassroom.controller.js, client/app/account/settings/newClassroom/newclassroom.html, client/app/contact/contact.service.js, client/app/main/main.js, client/app/main/main.scss, client/app/student/student.service.js, client/index.html, server/api/contact/contact.model.js
this is so ugly shhhh don't worry about it
=> 31 new classroom closes #31

Gruntfile.js, bower.json, client/app/account/login/login.html, client/app/account/settings/newClassroom/newclassroom.controller.js, client/app/account/settings/newClassroom/newclassroom.html, client/app/account/settings/newClassroom/studentForm/studentForm.html, client/app/account/settings/settings.html, client/app/account/signup/signup.html, client/app/app.js, client/app/app.scss, client/app/main/conversation/conversation.html, client/app/main/main.html, client/app/main/main.scss, client/components/navbar/navbar.html, client/index.html
=> closes #50

bower.json, client/app/account/login/login.html, client/app/account/settings/newClassroom/newclassroom.controller.js, client/app/account/settings/newClassroom/newclassroom.html, client/app/account/settings/settings.html, client/app/account/signup/signup.html, client/app/main/conversation/conversation.html, client/app/main/main.controller.js, client/app/main/main.html, client/app/main/main.scss, client/components/auth/user.service.js, client/index.html, server/api/classroom/classroom.controller.js, server/api/student/student.controller.js, server/api/user/index.js, server/api/user/user.controller.js, server/api/user/user.socket.js, server/config/seed.js
Would like to start a discussion about how this should be done.  I guess I think I might need to create another state for the contacts drop down to get access to the contacts themselves.  Let me know what you think
=> 43 create dropdown classrooms closes #43 closes #44

Gruntfile.js, bower.json, client/app/app.scss, client/index.html
pull this pls
i replaced bootstrap with bootstrap-sass-official to be more lightweight and added angular-bootstrap
=> i did this on the wrong branch but

server/api/contact/contact.controller.js, server/api/contact/contact.model.js, server/api/contact/index.js
=> closes #62

client/app/account/settings/newClassroom/newclassroom.controller.js, client/app/account/settings/newClassroom/newclassroom.html, client/app/account/settings/newClassroom/studentForm/studentForm.directive.js, client/app/account/settings/settings.html, client/app/app.js, client/app/app.scss, client/app/editStudentForm/editStudentForm.directive.js, client/app/editStudentForm/editStudentForm.directive.spec.js, client/app/editStudentForm/editStudentForm.html, client/index.html
:|||||||||||||||
i am so sorry i did like nothing today (i learned a lot about directives though)
=> closes #39

server/api/contact/contact.controller.js, server/api/contact/contact.model.js, server/api/twilio/index.js, server/api/twilio/twilio.spec.js, server/config/environment/index.js, server/config/seed.js, server/routes.js
We are getting messages into the correct conversations!
=> Twiliorequest closes #64 closes #68

client/app/account/settings/newClassroom/studentForm/studentForm.directive.js, client/app/editStudentForm/editStudentForm.directive.js, client/app/main/classroom.html, client/app/main/classroom/classroom.controller.js, client/app/main/classrooms.html, client/app/main/classrooms/classrooms.controller.js, client/app/main/editClassroom.html, client/app/main/editClassroom/editClassroom.controller.js, client/app/main/editClassroom/editClassroom.controller.spec.js, client/app/main/main.js, client/index.html, server/api/classroom/classroom.controller.js, server/api/classroom/classroom.socket.js, server/api/student/student.controller.js, server/api/user/user.socket.js, server/config/seed.js
Here is the edit classroom view using Melissa's directives
I was trying to use sockets to update the classroom name in real time but I will put that in a different issue.  Everything else updates okay because you move to a different route.
=> 46 edit classroom closes #46

client/app/editStudentForm/editStudentForm.directive.js, client/app/main/classrooms/classrooms.controller.js, client/app/main/editClassroom/editClassroom.controller.js
didn't use sockets but I emitted up to a parent controller!
=> 75classroomsockets closes #75

server/api/contact/contact.model.js, server/api/twilio/index.js, server/api/twilio/twilio.socket.js, server/config/environment/development.js, server/routes.js
felt bad about not having contributed anything today so wrote this real quick.  it creates a contact if there isn't one but it doesn't do anything on the front end.  if you want me to write something for that before merging i will, just wasn't sure if we knew how we wanted that to display yet.
also be aware i changed seedDB to false, in case you need to change it back to true for your own purposes
=> closes #81 i guess

client/app/account/settings/newClassroom/editContact/editContact.directive.js, client/app/account/settings/newClassroom/editContact/editContact.directive.spec.js, client/app/account/settings/newClassroom/editContact/editContact.html, client/app/account/settings/newClassroom/newclassroom.controller.js, client/app/account/settings/newClassroom/newclassroom.html, client/app/account/settings/newClassroom/studentForm/studentForm.directive.js, client/app/account/settings/newClassroom/studentForm/studentForm.html, client/app/app.scss, client/app/editStudentForm/editStudentForm.directive.js, client/app/editStudentForm/editStudentForm.html, client/app/editStudentForm/editStudentForm.scss, client/app/main/classroom.html, client/app/main/classroom/classroom.controller.js, client/app/main/classrooms/classrooms.controller.js, client/app/main/conversation/conversation.html, client/app/main/conversation/conversation.scss, client/app/main/editClassroom.html, client/app/main/editClassroom/editClassroom.controller.js, client/app/main/main.html, client/components/navbar/navbar.html, client/components/tel/tel.filter.js, client/index.html, server/api/classroom/classroom.controller.js
I have a pull request here.  It closes two issues.  Please let me know what you think.  There is a bunch of repeated code that I think I could optimize somehow but right now this is what I got.
=> 73 editdeletecontacts closes #73 closes #74

client/app/directives/conversation/conversation.html, client/app/main/classroom/classroom.controller.js, client/app/main/main.scss
no more accordion on the main view :(  if someone wants to style it better please do
=> closes #95 accordion

client/app/directives/addStudentForm/addStudentForm.directive.js, client/app/main/classrooms/classrooms.controller.js
=> fixing some things

bower.json, client/app/account/settings/settings.html, client/app/directives/fileread/fileread.directive.js, client/app/main/main.scss, client/app/main/newClassroom/newclassroom.controller.js, client/app/main/newClassroom/newclassroom.html, client/app/main/newClassroom/studentRoster/studentRoster.controller.js, client/app/main/newClassroom/studentRoster/studentRoster.html, client/index.html, server/api/classroom/classroom.controller.js
csv parser is working and I did a little validation on uploading a file as well as changing how the student roster view looks.  Also caught that it wasn't saving the relationship to the database so I fixed that as well
=> csv parser closes #100

client/app/about/about.controller.js, client/app/about/about.controller.spec.js, client/app/app.scss, client/app/main/classroom/conversation/conversation.controller.js, client/app/main/classrooms/classrooms.controller.js, client/app/main/main.js, client/app/main/newClassroom/studentRoster/studentRoster.controller.js, client/app/main/newClassroom/studentRoster/studentRoster.html, client/app/main/newClassroom/studentRoster/studentRoster.scss, client/components/auth/auth.service.js, client/components/navbar/navbar.html, client/index.html
Here is my pull request, has some more things added onto the end
=> 106 objproblem closes #106

client/app/directives/addStudentForm/addStudentForm.directive.js, server/api/contact/contact.model.js, server/api/contact/contact.spec.js
tiny pull request for presave hook
=> 109 presave hook closes #109

client/app/directives/contactList/contactList.html, client/app/directives/contactList/contactList.scss, client/app/main/classroom/classroom.controller.js, client/app/main/classroom/conversation/conversation.controller.js, client/app/main/classrooms/classrooms.html, client/app/main/main.js
This is a solution but it is not the best.  This is something that should be refactored later
=> 105 styling active states closes #105

client/app/factories/conversation.service.js, client/app/main/classroom/classroom.controller.js, client/app/main/classroom/conversation/conversation.controller.js, client/app/main/classrooms/classrooms.controller.js, client/index.html, server/api/conversation/conversation.controller.js, server/api/conversation/index.js
it's not pretty and i don't like it, but i did what i set out to do
=> closes #110 closes #114

client/app/account/login/login.controller.js, client/app/factories/newClass/newClass.service.js, client/app/factories/newClass/newClass.service.spec.js, client/app/main/classroom/classroom.controller.js, client/app/main/classrooms/classrooms.controller.js, client/app/main/editClassroom/editClassroom.controller.js, client/app/main/main.js, client/app/main/newClassroom/newclassroom.controller.js, client/app/main/newClassroom/studentRoster/studentRoster.controller.js, client/components/navbar/navbar.controller.js, client/components/navbar/navbar.html, client/index.html
So I think this is finally working.  Please look it over and let me know what you think.  Jordan gave me the idea for this random service to use a boolean.  It makes it kind of work perfectly...hopefully it doesn't mess with other things later
=> redirection close #123

client/app/directives/contactList/contactList.directive.js, client/app/directives/contactList/contactList.html
=> closes #118

client/app/directives/addContact/addContact.directive.js, client/app/directives/addStudentForm/addStudentForm.directive.js, client/app/directives/contactList/contactList.html, client/app/directives/editStudentForm/editStudentForm.directive.js, client/app/directives/editStudentForm/editStudentForm.html, client/app/main/classrooms/classrooms.controller.js, client/app/main/classrooms/groupMessager/groupMessager.controller.js, client/app/main/main.scss, server/api/contact/contact.model.js, server/api/student/student.model.js, server/api/student/student.spec.js
maybe this was a bad idea.  but i did it
=> closes #96

client/app/about/about.html
hosted videos on personal website
=> hosted videos
